// Mocks generated by Mockito 5.4.6 from annotations
// in todo/test/widget/todo_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo/data/repositories/todo_repository.dart' as _i2;
import 'package:todo/domain/models/todo_model.dart' as _i4;
import 'package:todo/ui/Todo/viewModel/todo_viewmodel.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeITodoRepository_0 extends _i1.SmartFake
    implements _i2.ITodoRepository {
  _FakeITodoRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoViewmodel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoViewmodel extends _i1.Mock implements _i3.TodoViewmodel {
  MockTodoViewmodel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITodoRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeITodoRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ITodoRepository);

  @override
  List<_i4.TodoModel> get todos =>
      (super.noSuchMethod(
            Invocation.getter(#todos),
            returnValue: <_i4.TodoModel>[],
          )
          as List<_i4.TodoModel>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  set todos(List<_i4.TodoModel>? _todos) => super.noSuchMethod(
    Invocation.setter(#todos, _todos),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(bool? _isLoading) => super.noSuchMethod(
    Invocation.setter(#isLoading, _isLoading),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> loadTodos() =>
      (super.noSuchMethod(
            Invocation.method(#loadTodos, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addTodo(String? title, String? description) =>
      (super.noSuchMethod(
            Invocation.method(#addTodo, [title, description]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleComplete(_i4.TodoModel? todo) =>
      (super.noSuchMethod(
            Invocation.method(#toggleComplete, [todo]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
